theme: jekyll-theme-slate
name: Rockford Lhotka
title: Rockford Lhotka
description: CTO at Magenic, creator of CSLA .NET, author, speaker
markdown: kramdown
permalink: /:year/:month/:day/:title
plugins:
  - jekyll-sitemap
github:
  is_project_page:
google_analytics: lhotka.net
